from .academic_semester import *
from .academic_year import *
from .assessment_item import *
from .bank_account import *
from .course_group_assement import *
from .Course import *
from .district import *
from .education_level import *
from .fee_item import *
from .fee_structure import *
from .intake import *
from .payments import *
from .payment_summary import *
from .programme import *
from .program_semester_payment import *
from .program_couser_structure import *
from .region import *
from .group import *
from .semester import *
from .semester_assessment import *
from .semester_result import *
from .status import *
from .student import *
from .student_registration import *
from .teaching_workload import *
from .user import *
