# Generated by Django 3.2.9 on 2022-01-27 13:01

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Semester',
                'verbose_name_plural': 'Academic Semester',
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Assessment Item',
                'verbose_name_plural': 'Assessment Item',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('NMB', 'NMB'), ('CRDB', 'CRDB'), ('BOA', 'BOA')], max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Account',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Course Group',
                'verbose_name_plural': 'Course Group',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'District',
            },
        ),
        migrations.CreateModel(
            name='GroupAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CA', 'Continuous Assessment'), ('ES', 'End of Semester')], default='CA', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('passmark', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.coursegroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.assessmentitem')),
            ],
            options={
                'verbose_name': 'course Group Assessment',
                'verbose_name_plural': 'course Group Assessment',
                'unique_together': {('item', 'category', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intake',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NTA-4', 'NTA-LEVEL 4'), ('NTA-5', 'NTA-LEVEL 5'), ('NTA-6', 'NTA-LEVEL 6')], max_length=45, unique=True)),
                ('year', models.CharField(editable=False, max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programme',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0.....'. Up to 10 digits allowed.", regex='[0][6-9][0-9]{8}')])),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('title', models.CharField(choices=[('staff', 'staff'), ('student', 'student'), ('tutor', 'tutor'), ('ICT Officer', 'ICT Officer'), ('System Administrator', 'System Administrator')], default='staff', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('parent_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0.....'. Up to 10 digits allowed.", regex='[0][6-9][0-9]{8}')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entry_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KCHS.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programme')),
                ('residency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KCHS.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Entry',
                'verbose_name_plural': 'Student Entry',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE'), ('PASS', 'PASS')], default='NOT PAID', max_length=30, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEMESTER ONE', 'SEMESTER ONE'), ('SEMESTER TWO', 'SEMESTER TWO'), ('SEMESTER THREE', 'SEMESTER THREE')], max_length=45, unique=True)),
                ('number', models.CharField(editable=False, max_length=45, unique=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Registration Status')),
                ('is_active', models.BooleanField(default=False)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KCHS.intake')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.level')),
                ('registerer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.academicsemester')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.student')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registration',
                'unique_together': {('student', 'semester', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'region',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KCHS.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.coursegroup')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.semester')),
            ],
            options={
                'verbose_name': 'Programme Course Structure',
                'verbose_name_plural': 'Programme Course Structure',
                'unique_together': {('semester', 'level', 'programme', 'group', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14, verbose_name='remain amount')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.bankaccount')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.registration')),
            ],
            options={
                'verbose_name': 'Registration Payment',
                'verbose_name_plural': 'Registration Payment',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intake',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Item',
                'verbose_name_plural': 'Fee Item',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.region'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'unique_together': {('financial_year', 'year')},
            },
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.academicyear'),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.semester'),
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programmecoursestructure')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching Workload',
                'verbose_name_plural': 'Teaching Workload',
                'unique_together': {('course', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='C A')),
                ('es', models.DecimalField(decimal_places=2, default='', max_digits=5, verbose_name='E S')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('remark', models.CharField(blank=True, max_length=90, null=True)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.academicsemester')),
                ('programme_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programmecoursestructure')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.registration')),
            ],
            options={
                'verbose_name': 'Academic Semester Result',
                'verbose_name_plural': 'Academic Semester Result',
                'unique_together': {('academic_semester', 'programme_course', 'registration')},
            },
        ),
        migrations.CreateModel(
            name='SemesterAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Marks/(100)')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.academicsemester')),
                ('assessment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.groupassessment')),
                ('programme_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programmecoursestructure')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.registration')),
            ],
            options={
                'verbose_name': 'Academic Semester Assessment',
                'verbose_name_plural': 'Academic Semester Assessment',
                'unique_together': {('academic_semester', 'programme_course', 'assessment_group', 'registration')},
            },
        ),
        migrations.CreateModel(
            name='PaymentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('minimum', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.bankaccount')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.semester')),
            ],
            options={
                'verbose_name': 'Programme Payment Structure',
                'verbose_name_plural': 'Programme Payment Structure',
                'unique_together': {('semester', 'level', 'programme', 'account')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.bankaccount')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.feeitem')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.programme')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KCHS.semester')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structure',
                'unique_together': {('fee', 'semester', 'level', 'account', 'programme')},
            },
        ),
    ]
