# Generated by Django 3.2.9 on 2022-03-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('NMB', 'NMB'), ('CRDB', 'CRDB'), ('BOA', 'BOA')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('FULL PAID', 'COMPLETE'), ('PASS', 'PASS'), ('PARTIAL PAID', 'PARTIAL PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14, verbose_name='remain amount')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KCHS.registration')),
            ],
            options={
                'verbose_name': 'Payment Summary',
                'verbose_name_plural': 'Payment Summary',
            },
        ),
    ]
