# Generated by Django 3.2.9 on 2022-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('CRDB', 'CRDB'), ('NMB', 'NMB'), ('BOA', 'BOA')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='es',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='E S'),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('FULL PAID', 'COMPLETE'), ('PASS', 'PASS'), ('PARTIAL PAID', 'PARTIAL PAID'), ('NOT PAID', 'NOT PAID'), ('SUPPLEMENTARY', 'SUPPLEMENTARY')], default='NOT PAID', max_length=30, unique=True),
        ),
    ]
