# Generated by Django 3.2.9 on 2022-04-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0002_auto_20220313_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('NMB', 'NMB'), ('BOA', 'BOA'), ('CRDB', 'CRDB')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='remain amount'),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('PARTIAL PAID', 'PARTIAL PAID'), ('NOT PAID', 'NOT PAID'), ('FULL PAID', 'COMPLETE'), ('PASS', 'PASS')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
