# Generated by Django 3.2.9 on 2022-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0003_auto_20220127_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('BOA', 'BOA'), ('CRDB', 'CRDB'), ('NMB', 'NMB')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('PASS', 'PASS'), ('PARTIAL PAID', 'PARTIAL PAID'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('FULL PAID', 'COMPLETE'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together={('academic_semester', 'programme_course', 'registration')},
        ),
    ]
