# Generated by Django 3.2.9 on 2022-01-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0004_auto_20220127_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('BOA', 'BOA'), ('NMB', 'NMB'), ('CRDB', 'CRDB')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE'), ('PASS', 'PASS'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
    ]
