# Generated by Django 3.2.9 on 2022-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0005_auto_20220127_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('PASS', 'PASS'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('NOT PAID', 'NOT PAID'), ('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together=set(),
        ),
    ]
