# Generated by Django 3.2.9 on 2022-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0006_auto_20220127_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('NMB', 'NMB'), ('CRDB', 'CRDB'), ('BOA', 'BOA')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PARTIAL PAID', 'PARTIAL PAID'), ('PASS', 'PASS'), ('FULL PAID', 'COMPLETE'), ('SUPPLEMENTARY', 'SUPPLEMENTARY')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together={('academic_semester', 'programme_course', 'registration')},
        ),
    ]
