# Generated by Django 3.2.9 on 2022-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0008_auto_20220128_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='College Logo')),
                ('Stump', models.ImageField(blank=True, null=True, upload_to='', verbose_name='College Stump')),
                ('Signature', models.ImageField(upload_to='', verbose_name='College Signature')),
            ],
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('BOA', 'BOA'), ('NMB', 'NMB'), ('CRDB', 'CRDB')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('PASS', 'PASS')], default='NOT PAID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('staff', 'staff'), ('Accountant', 'Accountant'), ('student', 'student'), ('tutor', 'tutor'), ('ICT Officer', 'ICT Officer'), ('System Administrator', 'System Administrator'), ('Director', 'Director')], default='staff', max_length=40),
        ),
    ]
