# Generated by Django 3.2.9 on 2022-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0009_auto_20220131_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('CRDB', 'CRDB'), ('NMB', 'NMB'), ('BOA', 'BOA')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='programmecoursestructure',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('FULL PAID', 'COMPLETE'), ('PARTIAL PAID', 'PARTIAL PAID'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('PASS', 'PASS'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
    ]
