# Generated by Django 3.2.9 on 2022-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KCHS', '0012_auto_20220312_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='due_currency',
        ),
        migrations.RemoveField(
            model_name='paymentstructure',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='paymentstructure',
            name='minimum_currency',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('NMB', 'NMB'), ('CRDB', 'CRDB'), ('BOA', 'BOA')], max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14, verbose_name='remain amount'),
        ),
        migrations.AlterField(
            model_name='paymentstructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='paymentstructure',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(choices=[('PARTIAL PAID', 'PARTIAL PAID'), ('FULL PAID', 'COMPLETE'), ('SUPPLEMENTARY', 'SUPPLEMENTARY'), ('PASS', 'PASS'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=30, unique=True),
        ),
    ]
